# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install

    sudo apt-get update
    sudo apt-get install mysql-server

    npm install express
    
    npm i body-parser

    npm run build
  displayName: 'npm install, MySQL, Express, body-parser and build'
